version: "3.8"

services:
  user-service:
    build:
      context: ./UserService/user-service/user-service
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: PlayList-UserService
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/Users # Use the local MongoDB URI
    networks:
      - playlist-network
    depends_on:
      - mongo # Ensure MongoDB is started before the UserService

  game-service:
    build:
      context: ./GameService
      dockerfile: Dockerfile
    image: game-service:latest
    container_name: PlayList-GameService
    ports:
      - "50051:50051"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Games # Same local MongoDB URI
    networks:
      - playlist-network
    depends_on:
      - mongo # Ensure MongoDB is started before the GameService

  rating-service:
    build:
      context: ./RatingService/rating_service
      dockerfile: Dockerfile
    image: rating-service:latest
    container_name: PlayList-RatingService
    ports:
      - "8081:8081"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - MP_MESSAGING_CONNECTOR_SMALLRYE_AMQP_HOST=rabbitmq
      - MP_MESSAGING_CONNECTOR_SMALLRYE_AMQP_PORT=5672
      - MP_MESSAGING_CONNECTOR_SMALLRYE_AMQP_USERNAME=guest
      - MP_MESSAGING_CONNECTOR_SMALLRYE_AMQP_PASSWORD=guest
      - QUARKUS_HTTP_PORT=8081 # <<--- ADDED THIS LINE
    networks:
      - playlist-network
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest # Pull the latest MongoDB image from Docker Hub
    container_name: mongo
    ports:
      - "27017:27017" # Map port 27017 (MongoDB default) on localhost to container
    networks:
      - playlist-network
    volumes:
      - mongo-data:/data/db # Persist MongoDB data to a Docker volume

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ENABLED_PLUGINS_FILE: /etc/rabbitmq/enabled_plugins
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - playlist-network

  web-gateway:
    build:
      context: ./WebGateway/webgateway
      dockerfile: Dockerfile
    image: web-gateway:latest
    container_name: PlayList-WebGateway
    ports:
      - "8083:8083"
    networks:
      - playlist-network
    depends_on:
      - user-service
      - rating-service
      - game-service

  mobile-gateway:
    build:
      context: ./MobileGateway
      dockerfile: Dockerfile
    image: mobile-gateway:latest
    container_name: PlayList-MobileGateway
    ports:
      - "3001:3001"
    networks:
      - playlist-network
    depends_on:
      - user-service
      - rating-service
      - game-service

  user-mfe:
    build: ./UserInterface/user-mfe
    image: user-mfe:latest
    container_name: PlayList-UserMFE
    ports:
      - "4174:80"
    networks:
      - playlist-network

  games-mfe:
    build: ./UserInterface/games-mfe
    image: games-mfe:latest
    container_name: PlayList-GamesMFE
    ports:
      - "4175:80"
    networks:
      - playlist-network

  ratings-mfe:
    build: ./UserInterface/ratings-mfe
    image: ratings-mfe:latest
    container_name: PlayList-RatingsMFE
    ports:
      - "4176:80"
    networks:
      - playlist-network

  host:
    build: ./UserInterface/host
    image: host:latest
    container_name: PlayList-HostApp
    ports:
      - "5173:80"
    networks:
      - playlist-network

networks:
  playlist-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
