version: "3.8"

services:
  user-service:
    build:
      context: ./UserService/user-service/user-service
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: PlayList-UserService
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/Users # Use the local MongoDB URI
    networks:
      - playlist-network
    depends_on:
      - mongo # Ensure MongoDB is started before the UserService

  game-service:
    build:
      context: ./GameService
      dockerfile: Dockerfile
    image: game-service:latest
    container_name: PlayList-GameService
    ports:
      - "50051:50051"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Games # Same local MongoDB URI
    networks:
      - playlist-network
    depends_on:
      - mongo # Ensure MongoDB is started before the GameService

  mongo:
    image: mongo:latest # Pull the latest MongoDB image from Docker Hub
    container_name: mongo
    ports:
      - "27017:27017" # Map port 27017 (MongoDB default) on localhost to container
    networks:
      - playlist-network
    volumes:
      - mongo-data:/data/db # Persist MongoDB data to a Docker volume

networks:
  playlist-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
