// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/game.proto

package gamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Developer     string                 `protobuf:"bytes,5,opt,name=developer,proto3" json:"developer,omitempty"`
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Game) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Game) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Game) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *Game) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GameIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameIdRequest) Reset() {
	*x = GameIdRequest{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameIdRequest) ProtoMessage() {}

func (x *GameIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameIdRequest.ProtoReflect.Descriptor instead.
func (*GameIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GameSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSearchRequest) Reset() {
	*x = GameSearchRequest{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSearchRequest) ProtoMessage() {}

func (x *GameSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSearchRequest.ProtoReflect.Descriptor instead.
func (*GameSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type WishListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishListRequest) Reset() {
	*x = WishListRequest{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishListRequest) ProtoMessage() {}

func (x *WishListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishListRequest.ProtoReflect.Descriptor instead.
func (*WishListRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *WishListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WishListRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GameListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameListResponse) Reset() {
	*x = GameListResponse{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameListResponse) ProtoMessage() {}

func (x *GameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameListResponse.ProtoReflect.Descriptor instead.
func (*GameListResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameListResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type WishListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishListResponse) Reset() {
	*x = WishListResponse{}
	mi := &file_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishListResponse) ProtoMessage() {}

func (x *WishListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishListResponse.ProtoReflect.Descriptor instead.
func (*WishListResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *WishListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\"\x9f\x01\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12!\n" +
	"\frelease_date\x18\x04 \x01(\tR\vreleaseDate\x12\x1c\n" +
	"\tdeveloper\x18\x05 \x01(\tR\tdeveloper\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\"\x1f\n" +
	"\rGameIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x11GameSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"C\n" +
	"\x0fWishListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\fGameResponse\x12\x1e\n" +
	"\x04game\x18\x01 \x01(\v2\n" +
	".game.GameR\x04game\"4\n" +
	"\x10GameListResponse\x12 \n" +
	"\x05games\x18\x01 \x03(\v2\n" +
	".game.GameR\x05games\",\n" +
	"\x10WishListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc4\x02\n" +
	"\vGameService\x126\n" +
	"\vGetGameById\x12\x13.game.GameIdRequest\x1a\x12.game.GameResponse\x12>\n" +
	"\vSearchGames\x12\x17.game.GameSearchRequest\x1a\x16.game.GameListResponse\x12>\n" +
	"\rAddToWishList\x12\x15.game.WishListRequest\x1a\x16.game.WishListResponse\x12C\n" +
	"\x12RemoveFromWishList\x12\x15.game.WishListRequest\x1a\x16.game.WishListResponse\x128\n" +
	"\vGetWishList\x12\x11.game.UserRequest\x1a\x16.game.GameListResponseB>Z<github.com/miha-plemenitas/PlayList/GameService/proto;gamepbb\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_game_proto_goTypes = []any{
	(*Game)(nil),              // 0: game.Game
	(*GameIdRequest)(nil),     // 1: game.GameIdRequest
	(*GameSearchRequest)(nil), // 2: game.GameSearchRequest
	(*WishListRequest)(nil),   // 3: game.WishListRequest
	(*UserRequest)(nil),       // 4: game.UserRequest
	(*GameResponse)(nil),      // 5: game.GameResponse
	(*GameListResponse)(nil),  // 6: game.GameListResponse
	(*WishListResponse)(nil),  // 7: game.WishListResponse
}
var file_proto_game_proto_depIdxs = []int32{
	0, // 0: game.GameResponse.game:type_name -> game.Game
	0, // 1: game.GameListResponse.games:type_name -> game.Game
	1, // 2: game.GameService.GetGameById:input_type -> game.GameIdRequest
	2, // 3: game.GameService.SearchGames:input_type -> game.GameSearchRequest
	3, // 4: game.GameService.AddToWishList:input_type -> game.WishListRequest
	3, // 5: game.GameService.RemoveFromWishList:input_type -> game.WishListRequest
	4, // 6: game.GameService.GetWishList:input_type -> game.UserRequest
	5, // 7: game.GameService.GetGameById:output_type -> game.GameResponse
	6, // 8: game.GameService.SearchGames:output_type -> game.GameListResponse
	7, // 9: game.GameService.AddToWishList:output_type -> game.WishListResponse
	7, // 10: game.GameService.RemoveFromWishList:output_type -> game.WishListResponse
	6, // 11: game.GameService.GetWishList:output_type -> game.GameListResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
