// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/game.proto

package gamepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetGameById_FullMethodName        = "/game.GameService/GetGameById"
	GameService_SearchGames_FullMethodName        = "/game.GameService/SearchGames"
	GameService_AddToWishList_FullMethodName      = "/game.GameService/AddToWishList"
	GameService_RemoveFromWishList_FullMethodName = "/game.GameService/RemoveFromWishList"
	GameService_GetWishList_FullMethodName        = "/game.GameService/GetWishList"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	GetGameById(ctx context.Context, in *GameIdRequest, opts ...grpc.CallOption) (*GameResponse, error)
	SearchGames(ctx context.Context, in *GameSearchRequest, opts ...grpc.CallOption) (*GameListResponse, error)
	AddToWishList(ctx context.Context, in *WishListRequest, opts ...grpc.CallOption) (*WishListResponse, error)
	RemoveFromWishList(ctx context.Context, in *WishListRequest, opts ...grpc.CallOption) (*WishListResponse, error)
	GetWishList(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GameListResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetGameById(ctx context.Context, in *GameIdRequest, opts ...grpc.CallOption) (*GameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SearchGames(ctx context.Context, in *GameSearchRequest, opts ...grpc.CallOption) (*GameListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameListResponse)
	err := c.cc.Invoke(ctx, GameService_SearchGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AddToWishList(ctx context.Context, in *WishListRequest, opts ...grpc.CallOption) (*WishListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishListResponse)
	err := c.cc.Invoke(ctx, GameService_AddToWishList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) RemoveFromWishList(ctx context.Context, in *WishListRequest, opts ...grpc.CallOption) (*WishListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WishListResponse)
	err := c.cc.Invoke(ctx, GameService_RemoveFromWishList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetWishList(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GameListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameListResponse)
	err := c.cc.Invoke(ctx, GameService_GetWishList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	GetGameById(context.Context, *GameIdRequest) (*GameResponse, error)
	SearchGames(context.Context, *GameSearchRequest) (*GameListResponse, error)
	AddToWishList(context.Context, *WishListRequest) (*WishListResponse, error)
	RemoveFromWishList(context.Context, *WishListRequest) (*WishListResponse, error)
	GetWishList(context.Context, *UserRequest) (*GameListResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetGameById(context.Context, *GameIdRequest) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameById not implemented")
}
func (UnimplementedGameServiceServer) SearchGames(context.Context, *GameSearchRequest) (*GameListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGames not implemented")
}
func (UnimplementedGameServiceServer) AddToWishList(context.Context, *WishListRequest) (*WishListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWishList not implemented")
}
func (UnimplementedGameServiceServer) RemoveFromWishList(context.Context, *WishListRequest) (*WishListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromWishList not implemented")
}
func (UnimplementedGameServiceServer) GetWishList(context.Context, *UserRequest) (*GameListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWishList not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetGameById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameById(ctx, req.(*GameIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SearchGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SearchGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_SearchGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SearchGames(ctx, req.(*GameSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AddToWishList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WishListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AddToWishList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_AddToWishList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AddToWishList(ctx, req.(*WishListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_RemoveFromWishList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WishListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).RemoveFromWishList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_RemoveFromWishList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).RemoveFromWishList(ctx, req.(*WishListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetWishList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetWishList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetWishList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetWishList(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameById",
			Handler:    _GameService_GetGameById_Handler,
		},
		{
			MethodName: "SearchGames",
			Handler:    _GameService_SearchGames_Handler,
		},
		{
			MethodName: "AddToWishList",
			Handler:    _GameService_AddToWishList_Handler,
		},
		{
			MethodName: "RemoveFromWishList",
			Handler:    _GameService_RemoveFromWishList_Handler,
		},
		{
			MethodName: "GetWishList",
			Handler:    _GameService_GetWishList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game.proto",
}
