server:
  port: 8083

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://playlist-userservice:8080
            predicates:
              - Path=/users/**

          - id: rating-service
            uri: http://playlist-ratingservice:8081
            predicates:
              - Path=/ratings/**, /comments/**

          - id: game-service
            uri: http://playlist-gameservice:8082
            predicates:
              - Path=/games/**
      default-filters:
        - AddResponseHeader=X-Response-Time, ${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info
