server:
  port: 8083

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://PlayList-UserService:8080
            predicates:
              - Path=/users/**, /wishlists/**

          - id: rating-service
            uri: http://PlayList-RatingService:8081
            predicates:
              - Path=/ratings/**, /comments/**

          - id: game-service
            uri: http://PlayList-GameProxy:8082
            predicates:
              - Path=/games/**

      default-filters:
        - AddResponseHeader=X-Response-Time, ${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.playlist.webgateway: DEBUG
