name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      #########################
      # 🧪 UserService (Java) #
      #########################
      - name: Run Maven tests
        working-directory: ./UserService/user-service/user-service
        run: |
          chmod +x mvnw
          ./mvnw test

      ##########################
      # ✅ GameService (Go)    #
      ##########################
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run Go unit tests
        working-directory: ./GameService
        run: |
          go test ./tests -v

      #########################
      # 🐳 Docker Setup       #
      #########################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build UserService Docker image
        run: |
          docker build -f UserService/user-service/user-service/Dockerfile -t user-service ./UserService/user-service/user-service

      - name: Build GameService Docker image
        run: |
          docker build -f GameService/Dockerfile -t game-service ./GameService
