name: CI Workflow

# Trigger the workflow when pushing to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # You can use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Cache Docker layers to speed up the workflow
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -f UserService\user-service\user-service\Dockerfile -t user-service ./user-service

      # Run tests inside the Docker container
      - name: Run tests
        run: |
          docker run --rm user-service ./mvnw test  # Run your tests with Maven inside the Docker container
