name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd="mongosh --quiet --username root --password example --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      #########################
      #   UserService (Java)   #
      #########################
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Run Maven tests
        working-directory: ./UserService/user-service/user-service
        env:
          SPRING_DATA_MONGODB_URI: mongodb://root:example@localhost:27017/Users
        run: |
          chmod +x mvnw
          ./mvnw test

      ##########################
      #   GameService (Go)     #
      ##########################
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run Go unit tests
        working-directory: ./GameService
        run: |
          go test ./tests -v

      #########################
      #   Docker Setup        #
      #########################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build UserService Docker image
        run: |
          docker build -f UserService/user-service/user-service/Dockerfile -t user-service ./UserService/user-service/user-service

      - name: Build GameService Docker image
        run: |
          docker build -f GameService/Dockerfile -t game-service ./GameService
