version: "3.8"

services:
  user-service:
    image: user-service:latest # Use the image you created earlier
    container_name: PlayList-UserService # Name of your container
    ports:
      - "8080:8080" # Map port 8080 inside the container to port 8080 on your host
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://Miha:miha123@playlistcluster.jy8zn.mongodb.net/Users?retryWrites=true&w=majority&appName=PlayListCluster
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge
